import React from "react";
import Head from "next/head";
import { dehydrate, useQuery } from "react-query";
import { queryClient, getCategories, getFandoms } from "../src/api";

import { Header, Sidebar, Reels, Banner } from "../components";

export async function getServerSideProps() {
  await queryClient.prefetchQuery("categories", () => getCategories());

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

const Content = ({ children }: { children: any }) => {
  const [bannerActive, setBannerActive] = React.useState(false);

  const { data } = useQuery(["categories"], () => getCategories());

  console.log(data?.categories);

  return (
    <>
      <Head>
        <title>UNILIB - Український форум</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setBannerActive={setBannerActive} />
      <main className={"main"}>
        <div className="container main-content flex-row flex-space">
          <Sidebar />
          <div id="content" className="container">
            {children}
          </div>
          <Reels />
        </div>
      </main>
      <Banner bannerActive={bannerActive} setBannerActive={setBannerActive} />
      <footer className={"colophon"}></footer>
    </>
  );
};

export default Content;
