import React from "react";
import Head from "next/head";

import { Header, Sidebar, Reels, Banner } from "../components";

const Content = ({ children }: { children: any }) => {
  const [bannerActive, setBannerActive] = React.useState(false);

  return (
    <>
      <Head>
        <title>UNILIB - Український форум</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setBannerActive={setBannerActive} />
      <main className={"main"}>
        <div className="container main-content flex-row flex-space">
          <Sidebar />
          <div id="content" className="container">
            {children}
          </div>
          <Reels />
        </div>
      </main>
      <Banner bannerActive={bannerActive} setBannerActive={setBannerActive} />
      <footer className={"colophon"}></footer>
    </>
  );
};

export default Content;
