import "../styles/globals.scss";
import { useState } from "react";
import type { AppProps } from "next/app";
import Head from "next/head";

// Apollo staff
import { ApolloProvider } from "@apollo/client";
import { client } from "../graphql/apollo-client";

// Nextauth staff
import { SessionProvider } from "next-auth/react";

import { Header, Banner, Sidebar, Reels } from "../components";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  const [bannerActive, setBannerActive] = useState(false);

  return (
    <ApolloProvider client={client}>
      <SessionProvider session={session}>
        <Head>
          <title>UNILIB - Український форум</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header setBannerActive={setBannerActive} />
        <main className="main">
          <div className="container main-content flex-row flex-space">
            <Sidebar categories={[]} fandoms={[]} />
            <Component {...pageProps} />
            <Reels />
          </div>
        </main>
        <Banner bannerActive={bannerActive} setBannerActive={setBannerActive} />
        <footer className={"colophon"}></footer>
      </SessionProvider>
    </ApolloProvider>
  );
}
