import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Banner, Content, Header, Post, Reels, Sidebar } from "../components";

import image from "../public/images/404.png";

const FourOhFour = () => {
  const [bannerActive, setBannerActive] = React.useState(false);

  return (
    <>
      <Head>
        <title>UNILIB - Ukrainian forum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setBannerActive={setBannerActive} />
      <main className={"main"}>
        <div className="container main-content flex-row flex-space">
          <Sidebar />
          <Content>
            <Post
              group="UNILIB"
              name="Admin"
              time="00:00"
              title="404 - Сторінка не найдена"
              likesCount={0}
              commentsCount={0}
              isFailPage={true}
            >
              <p>
                Походу ви зайшли сюди помилково а можливо й спеціально
                (дивакувата ви людина), але вам досі доступний увесь контент на
                сайті тому просто оберіть фендом зліва або перейдіть у те що
                часто обговорюються сьогодні з справа.
              </p>
              <div className="image-holder container">
                <Image src={image} alt="404-image" />
              </div>
              <p>
                Тут ми вирішили прикипіти якусь цікаво картинку щоб ви зря час
                не витрачали. Хоча ви й так витрачаєте свій час...
              </p>
            </Post>
          </Content>
          <Reels />
        </div>
      </main>
      <Banner bannerActive={bannerActive} setBannerActive={setBannerActive} />
      <footer className={"colophon"}></footer>
    </>
  );
};

export default FourOhFour;
