import Head from "next/head";
import { Header, Sidebar } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>UNILIB - Ukrainian forum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={"main"}>
        <div className="container main-content flex-row flex-space">
          <Sidebar />
        </div>
      </main>
      <footer className={"colophon"}></footer>
    </>
  );
}
